name: Deploy Dockerized Backend to EC2

on:
  push:
    paths:
      - 'server/**'
      - 'compose.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or whatever version you're using

      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Run backend tests
        working-directory: server
        run: npm run test

      # ✅ If tests pass, only then deploy
      - name: SSH into EC2 and deploy Docker
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/AddVenture
            git pull origin main

            # stop any old containers
            docker compose -f compose.yml down

            # rebuild and restart backend
            docker compose -f compose.yml up -d --build

            # prune dangling images to save space
            docker image prune -f
          script_stop: true
          debug: false
        envs_format: "export"
        shell: bash
