name: Deploy Backend to EC2

on:
  push:
    paths:
      - 'server/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }} 
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/AddVenture
            git pull origin main
            cd server
            npm ci
            pm2 restart index.js || pm2 start index.js
