name: Deploy Dockerized Backend to EC2

on:
  push:
    paths:
      - 'server/**'
      - 'compose.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/AddVenture
            git pull origin main

            # stop any old containers
            docker compose -f compose.yml down

            # rebuild and restart backend
            docker compose -f compose.yml up -d --build

            # prune dangling images to save space (optional)
            docker image prune -f
